version: "3.9"
services:
        web:
                build: .
        cyclonedx:
                image: "cyclonedx/cyclonedx-cli"
                #        dotnet:
                #image: "cyclonedx/cyclonedx-dotnet"
                # python:
                #image: "cyclonedx/cyclonedx-python"
