From debian:latest

RUN apt-get update

RUN apt install -y git

RUN apt install -y curl

RUN apt-get -y install python3
RUN apt-get -y install python3-setuptools
RUN apt-get -y install python3-pip
RUN apt-get -y install npm

RUN git clone https://github.com/CycloneDX/cyclonedx-core-java.git

RUN git clone https://github.com/CycloneDX/cyclonedx-dotnet.git

#Volume volu

RUN git clone https://github.com/skeeto/sample-java-project.git

WORKDIR sample-java-project

#copy sample-java-project /volu
#COPY ./app /volume2

RUN npm install --include-dev

RUN npm install -g @cyclonedx/bom

RUN curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
RUN curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
